/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.pecrom.view.main;

import javax.swing.*;

/**
 * @author pecrom
 */
public class Desktop_Form extends javax.swing.JPanel {

  /**
   * Creates new form Desktop_Form
   */
  public Desktop_Form() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */

  public void addInternalFrame(JComponent view) {
    JInternalFrame frame = new JInternalFrame("test", true, true, true, true);
    frame.add(view);
    frame.setSize(view.getPreferredSize());
    desktopPane.add(frame);
    frame.setVisible(true);

    desktopPane.revalidate();
    desktopPane.repaint();

  }

  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    desktopPane = new javax.swing.JDesktopPane();
    jInternalFrame1 = new javax.swing.JInternalFrame();

    desktopPane.setName("desktopPane"); // NOI18N

    jInternalFrame1.setName("jInternalFrame1"); // NOI18N
    jInternalFrame1.setVisible(true);

    javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
    jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
    jInternalFrame1Layout.setHorizontalGroup(
      jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 11, Short.MAX_VALUE)
    );
    jInternalFrame1Layout.setVerticalGroup(
      jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 0, Short.MAX_VALUE)
    );

    jInternalFrame1.setBounds(60, 50, 23, 31);
    desktopPane.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JDesktopPane desktopPane;
  private javax.swing.JInternalFrame jInternalFrame1;
  // End of variables declaration//GEN-END:variables
}
